### ISSUE TITLE
[suggestion] precompile postint into package and execute it only once on installation then remove it

### ISSUE THREAD

**Issue by Kunderscore** [Muirey03/Cr4shed#10]
The way you have set it up right now, it seems the user would be required to have postint installed on their devices after installing your whole pacakge.

So, theoretically, we could precompile postint with theos, put it in `layout/usr/bin` execute it on package installation by putting the following line in `Makefile`
```
after-install::
	install.exec "postint && rm /usr/bin/postint"
```
+ `/usr/bin` path prefix for where `postint` to be temporarily located should be changed to `/tmp`, as it would get cleans on reboot, but that disable jailbreak, but we can always use `rm`
+  if i ever tried myself i would post the result ( but i am having problem compiling your project )

P.S: 
I am quite fond of you project because my tweak `Avertas` is having problems on ppl's phone.
Ppl don't know how to get & send crash logs. So it would be great if your `cr4ashed` can be popularized, be a great alternative to crashreporter, at the same time beneficial to everyone !!

**Comment by Muirey03** [comment]
Well, postinst is removed now, but actually it worked perfectly as it was. If you see, I added `postinst_INSTALL_PATH = /DEBIAN` to the postinst's Makefile. This means that after it's compiled, postinst is added to the DEBIAN folder before being zipped into the deb. This means that the deb has the already compiled postinst file in its DEBIAN folder so will work flawlessly. I would recommend doing this every time you want to use a compiled postinst/preinst/prerm (as opposed to a shell script). Quick note, `after-install::` is executed by theos on install, it has nothing to do with apt/dpkg/cydia so you can't put anything there that you want to be executed on your users' devices. By the sounds of it, you haven't used postinst before, I would recommend this page on the iPhoneDevWiki: http://iphonedevwiki.net/index.php/Packaging. If you were to extract at a deb of 2.0.1 (postinst was remove in 2.0.2), you would see the postinst is correctly placed and is already compiled.

PS:
So glad it's come in useful for you. Thank you for being so active on this GitHub repo btw, super appreciated 👍

**Comment by Kunderscore** [comment]
Okay, through mistake i shall learn. Much thanks
