### ISSUE TITLE
[Compiling] MobileGestalt MGCopyAnswer header and symbol definition error 

### ISSUE THREAD

**Issue by Inc0ns1st3nt** [Muirey03/Cr4shed#11]
Header definition issue:
```
~/sources/ios/git/Cr4shed/symbolication.h:9:32: error: no matching function for call to 'MGCopyAnswer'
    return (__bridge NSString*)MGCopyAnswer(kMGCPUArchitecture);
                               ^~~~~~~~~~~~
......
Tweak.xm:93:32: error: no matching function for call to 'MGCopyAnswer'
    return (__bridge NSString*)MGCopyAnswer(CFSTR("marketing-name"));
                               ^~~~~~~~~~~~
~/theos/vendor/include/MobileGestalt/MobileGestalt.h:31:15: note: candidate function not viable: requires 2 arguments, but 1 was provided
    CFTypeRef MGCopyAnswer(CFStringRef question, CFDictionaryRef options);
```
Symbol definition issue when `CFTypeRef MGCopyAnswer(CFStringRef question);` is put before
```
#import "symbolication.h"
```
```
Undefined symbols for architecture arm64:
  "__Z12MGCopyAnswerPK10__CFString", referenced from:
      __Z7getArchv in Tweak.xm.dc223ef3.o
      __Z10deviceNamev in Tweak.xm.dc223ef3.o
```
Makefile included libraries:
```
Cr4shed_LIBRARIES = rocketbootstrap MobileGestalt bulletin
```
while `grep MGCopyAnswer ~/theos/sdks/iPhoneOS11.2.sdk/usr/lib/libMobileGestalt.tbd` shows
>     symbols:         [ _MGCancelNotifications, _MGCopyAnswer, _MGCopyAnswerWithError,

**Comment by Muirey03** [comment]
That's strange, not sure why your SDK expects two arguments for MGCopyAnswer. I compile it with the 9.2 sdk and that works perfectly for me.

**Comment by Muirey03** [comment]
Closing this as it isn't an issue with newer sdks. By the way, the reason it didn't work when you added `CFTypeRef MGCopyAnswer(CFStringRef question);` yourself is because `_MGCopyAnswer` is a C symbol and you put in a C++ file with using `extern "C"`.
