### ISSUE TITLE
Face ID and Music app not working 

### ISSUE THREAD

**Issue by hasanx64** [Muirey03/Cr4shed#12]
Face ID does not work when opening apps and Music app won’t play music.  Version: 2.0.4

**Comment by hasanx64** [comment]
Is this being looked into? Do you need any further info from me about this? Thank you!

**Comment by hasanx64** [comment]
Is anyone looking into this issue?

**Comment by Muirey03** [comment]
Fixed in 2.0.5

**Comment by hasanx64** [comment]
This issue is still happening even with version 2.0.6
