### ISSUE TITLE
Request - Quiet Notifications

### ISSUE THREAD

**Issue by fillupontacos** [Muirey03/Cr4shed#14]
Is there a way to get notifications of crashes to deliver quietly? So not on lock screen only in notification center. Thanks.

**Comment by NSExceptional** [comment]
![image](https://user-images.githubusercontent.com/8371943/70360459-3be61a80-1844-11ea-9aca-52ae5a50b55d.jpg)

**Comment by fillupontacos** [comment]
I think the issue fixed itself after a more recent update. Working now, thank you!

Regards,

Phil Gigliotti

On Dec 6, 2019, at 5:20 PM, Tanner Bennett <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #14<https://github.com/Muirey03/Cr4shed/issues/14>.
