### ISSUE TITLE
Can’t install

### ISSUE THREAD

**Issue by notoriouszero** [Muirey03/Cr4shed#15]
![52E19DCD-8674-4961-98CA-8A1BC8252193](https://user-images.githubusercontent.com/48587412/54423473-fbe77200-46cd-11e9-8dba-8520e1a235c7.png)

In Cydia it says that’s phone is compatible and I get this issue after I try installing.

**Comment by Muirey03** [comment]
You need to add the repo: https://rpetri.ch/repo/
