### ISSUE TITLE
Installing cr4shed makes cydia constantly give errors

### ISSUE THREAD

**Issue by ar300500** [Muirey03/Cr4shed#17]
When installing I get cydo exited unexpectedly then followed by constant errors as shown in this screenshot:

https://imgur.com/a/oLRuGNz

After respringing cydia will continue to show those errors stopping you from using cydia to do anything. Errors go away when the dylibs for cr4shed are either disabled with icleaner or disabled then uninstalled in cydia.

I am on iOS 10.3.1 iPhone 7 Plus running meridian jailbreak.

**Comment by Muirey03** [comment]
This isn't really an issue with Cr4shed itself and there's nothing I can do about this on my end so I'm closing it.
