### ISSUE TITLE
iPad Pro 12.1.1

### ISSUE THREAD

**Issue by motoissa** [Muirey03/Cr4shed#2]
Was working fine but then it keeps crashing 
[2019-02-25_00:15.log](https://github.com/Muirey03/Cr4shed/files/2899197/2019-02-25_00.15.log)

**Comment by Kunderscore** [comment]
What keeps crashing? from your log file it seems to be Preference app, furthermore it could be deduced as a tweak conflict, and that you should contact the tweak author instead.

**Comment by Muirey03** [comment]
Fixed in 2.0
