### ISSUE TITLE
Cr4shed Making Apps Crash/Not working properly

### ISSUE THREAD

**Issue by KeyFlyz** [Muirey03/Cr4shed#20]
When I have this installed ebay app crashes when opening, and It’s not showing all crashes. iPhone 8+ IOS 12.0.1 unc0ver b48.

**Comment by kirpeace** [comment]
Mobikwik wallet detecting jailbreak and shows jail broken even after adding it in Liberty lite or other apps. I removed it and app started working

**Comment by NSExceptional** [comment]
If there's no log and it crashes on launch, then it's not actually crashing, it's just never launching. Try reinstalling the app. Closing this unless more info is provided
