### ISSUE TITLE
Cr4shed (cr4shed.dylib) overtime causes some apps to hang on inital load and prevent Music app for playing anything

### ISSUE THREAD

**Issue by AltF5** [Muirey03/Cr4shed#21]
- Tested on iP8, iOS 11.3
- Note: Cr4shedSB.dylib does not create these problems when enabled; its specific to Cr4shed.dylib. Seeing in its plist it hooks into com.apple.security, it must have something to do with that being tripped up. This explains why reboots were neccessary after disabling dylibs (and not just repsprings) since this didn't hook into springboard.

Unclear what update included Cr4shed as a depdance and installed it, but I am uninstalling now due to these issues which were annoying to say the least.

**Comment by Muirey03** [comment]
Try installing WorkFFS and seeing if that fixes it.

**Comment by AltF5** [comment]
Good to know. If I happen to reinstall it or it crops up as a neccessary dependency then I’ll try. It was a strange one indeed.
