### ISSUE TITLE
Fails most of the time on iOS 10.2.1

### ISSUE THREAD

**Issue by badger200** [Muirey03/Cr4shed#24]
iPad Pro 9.7" 
iOS 10.2.1 with doubleh3lix JB. 

Cr4shed worked maybe 2-3 times out of thousands of crashes CrashReporter caught. Not sure why. I tried updating a bunch of stuff including CrashReporter itself from 2.0.8 to 2.0.9 and now I keep getting endless CrashReporter crashes of itself every 30 seconds, in a loop, that won't stop until I reboot. It's generated hundreds and hundreds of crash logs of itself.

**Comment by badger200** [comment]
2.0.9 and 2.0.8 do it endlessly. Now I'm trying 2.0.7 and I'll see how it goes, it's working so far. It's always a crash in libnotificationd. I've tried both 2.0-2 and 2.0-3 versions of libnotificationd and no difference. 

It's always this same error:

Date: 2019-08-21 11:20:02 +0000
Process: libnotificationd
Bundle id: (null)
Exception type: NSInvalidArgumentException
Reason: -[UNUserNotificationCenter initWithBundleProxy:]: unrecognized selector sent to instance 0x10041cef0
Culprit: Unknown
Device: iPad Pro, iOS 10.2.1
Call stack:
0   CoreFoundation                      0x0000000184d451d0 __exceptionPreprocess
1   libobjc.A.dylib                     0x000000018377c55c objc_exception_throw
2   CoreFoundation                      0x0000000184d4c268 __methodDescriptionForSelector
3   CoreFoundation                      0x0000000184d49270 ___forwarding___
4   CoreFoundation                      0x0000000184c4280c _CF_forwarding_prep_0
5   libnotificationd                    0x00000001000efdc0 __libnotificationd_event_handler_block_invoke
6   libxpc.dylib                        0x0000000183e178f4 _xpc_connection_call_event_handler
7   libxpc.dylib                        0x0000000183e153e8 _xpc_connection_mach_event
8   libdispatch.dylib                   0x0000000183bce28c _dispatch_client_callout4
9   libdispatch.dylib                   0x0000000183bd1d80 _dispatch_mach_msg_invoke
10  libdispatch.dylib                   0x0000000183bdc210 _dispatch_queue_serial_drain
11  libdispatch.dylib                   0x0000000183bd11e0 _dispatch_mach_invoke
12  libdispatch.dylib                   0x0000000183bdd26c _dispatch_root_queue_drain_deferred_item
13  libdispatch.dylib                   0x0000000183be3af8 _dispatch_kevent_worker_thread
14  libsystem_pthread.dylib             0x0000000183dd714c _pthread_wqthread
15  libsystem_pthread.dylib             0x0000000183dd6d8c start_wqthread

**Comment by badger200** [comment]
Update: seems to work using slightly older BigBoss repo CrashReporter & its 3 support libraries, instead of newer CokePokes version of CrashReporter & its 3 support libraries.

**Comment by NSExceptional** [comment]
The CokePokes stuff breaks things, yeah. Closing this
