### ISSUE TITLE
Runaway constant endless ReportCrash crashes 

### ISSUE THREAD

**Issue by badger200** [Muirey03/Cr4shed#29]
In the past week I updated from my last bug report, iOS 10.2.1 w/doubleh3lix > 12.4 w/unc0ver 3.6.1. 

However I still have basically the same issues, actually worse. Every time I install it and respring, my system becomes sluggish and CocoaTop reveals ReportCrash crashes, which Cr4shed reports in Notifications again and again, and even issuing “killall -9 ReportCrash” usually does not interrupt this runaway process cycle. 

I also tried downgrading to 2.0.9 and had the same problem. There were a few times where the crashing DID cease, but it always seems to come back on next reboot/respring. 

Is there anyone for whom Cr4shed is working properly? Especially on 12.4?

**Comment by badger200** [comment]
Update: seems to work using slightly older BigBoss repo CrashReporter & its 3 support libraries, instead of newer CokePokes version of CrashReporter & its 3 support libraries. 

Aa soon as I removed all CokePokes CrashReporter components in Cydia, then installed plain CrashReporter from BigBoss, within the hour I saw my first functioning cr4shed and CrashReporter activities.

**Comment by NSExceptional** [comment]
Yeah, don't use the CokePokes stuff. I've never used it and I've never had any issues. Gonna close this for now since your issue seems resolved.
