### ISSUE TITLE
Cr4shed 3.0.1 crashes.

### ISSUE THREAD

**Issue by ziyaado** [Muirey03/Cr4shed#30]
‪Hello‬
‪Cr4shed Ver. 3.0.1 is causing SB crashes.‬
‪I downgraded it, read the crash log and found BatteryLife is the culprit.‬

‪I have verified this 3 times. I’m not sure if the problem is with BatteryLife or cr4shed.‬
‪I’m just letting you know.

I am not sure how to upload the log here. Does making screenshots from cr4shed help?

Thank you!

**Comment by ziyaado** [comment]
https://pastebin.com/UWHTfgWQ
The log is here

**Comment by 1nc0ns1st3nt** [comment]
cr4sh is a tool for you to see the crash logs, and should not crash your device.
As you can see in the crash log as well
```
Culprit: batteryLife.dylib
Call stack:
0   CoreFoundation                      0x00000001a75329a4 __exceptionPreprocess
1   libobjc.A.dylib                     0x00000001a670b9f8 objc_exception_throw
2   CoreFoundation                      0x00000001a743cbc0 -[NSCache init]
3   Foundation                          0x00000001a7fd0a78 -[NSConcreteTask launchWithDictionary:error:]
4   batteryLife.dylib                   0x000000010b5bd45c batteryLife.dylib + 37980
5   batteryLife.dylib                   0x000000010b5be278 batteryLife.dylib + 41592
```
The log tells you that the reason of crash would be batteryLife

**Comment by NSExceptional** [comment]
@Muirey03 do you ever close issues like this? I'd be happy to start moderating here if you'd give me access. I have a few PRs ready too to greatly improve the app.

**Comment by Muirey03** [comment]
@NSExceptional thank you very much, I'd love some help managing all this. I haven't really been using GitHub a lot recently so it's getting a bit out of hand. I've been working on a major update to Cr4shed that should greatly improve its stability and reliability so once that's out I should be able to close the majority of these issues. Once I'm done with that, I'll definitely take a look at your PRs, the app part of Cr4shed is extremely bare-bones atm and could do with some serious improvements. I'll add you as a contributor now.

**Comment by NSExceptional** [comment]
Awesome! Thanks!

I'm gonna go ahead and close this one since it's obvious this is not an issue with Cr4shed.

**Comment by Muirey03** [comment]
@NSExceptional is there somewhere where we can discuss things? Do you have discord?

**Comment by NSExceptional** [comment]
iMessage at my GitHub email or Twitter! I'm also in a jailbreak developers slack I could have you added to

**Comment by Muirey03** [comment]
@NSExceptional Slack works well, what's the workspace url?

**Comment by NSExceptional** [comment]
What's your slack email? I have to get the admin to add you

**Comment by Muirey03** [comment]
@NSExceptional tommy.muir@btinternet.com

**Comment by NSExceptional** [comment]
Messaged him. I'm @objc in the slack. Wait for an email

**Comment by Muirey03** [comment]
Thank you
