### ISSUE TITLE
3.0.1 keeps crashing on Thread 3

### ISSUE THREAD

**Issue by Popcorncandy09** [Muirey03/Cr4shed#31]
Exception type: EXC_BAD_ACCESS
Exception subtype: KERN_PROTECTION_FAILURE: 0x102a3c000
Exception codes: 0x0000000000000002, 0x0000000102a3c000
Culprit: CrashReporter.dylib
VM Protection: rw-

**Comment by badger200** [comment]
Personal Update: seems to work using slightly older BigBoss repo CrashReporter & its 3 support libraries, instead of newer CokePokes version of CrashReporter & its 3 support libraries. 

If you’ve been using the CokePokes, definitely try my workaround.

**Comment by Muirey03** [comment]
Cokepokes' CrashReporter doesn't work on Unc0ver and causes ReportCrash to crash repeatedly. This is not an issue with Cr4shed at all.
