### ISSUE TITLE
Enable bounces on the log view

### ISSUE THREAD

**Issue by CreatureSurvive** [Muirey03/Cr4shed#37]
Enable scrollView bounces on the `CRALogController` for a more fluid feel in the UI. Currently scrolling stops are very rigid, and jarring. You can enable bounces using `[self.webView.scrollView setBounces:YES];` and it makes a world of difference. This does not have any negative effect on back gestures and also helps with readability when reading close to screen edges.

**Comment by Muirey03** [comment]
Not sure why I ever decided to disable bounces. I have re-enabled them now (see 9903e9f)
