### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by basilmslmani** [Muirey03/Cr4shed#4]
Crashes springboard , get you stuck in respringloop

**Comment by Kunderscore** [comment]
This tweak itself creates log files for crashes to debug, you could attach the log, and we can actually get a fix on the issue.
From your description:
Is it cr4shed, the tweak causing respring loop. Or is it the other tweak conflict with another.

**Comment by basilmslmani** [comment]
I can’t seem to find the crash logs via filza
I knew it caused the repairing loop because when I turned it off in iCleaner the respring worked
Thanks
Basil MSLMANI

On Mar 1, 2019, at 7:27 PM, Kunderscore <notifications@github.com<mailto:notifications@github.com>> wrote:


This tweak itself creates log files for crashes to debug, you could attach the log, and we can actually get a fix on the issue.
From your description:
Is it cr4shed, the tweak causing respring loop. Or is it the other tweak conflict with another.

**Comment by Muirey03** [comment]
Fixed in 2.0

**Comment by basilmslmani** [comment]
That escalated quickly
Gonna try now
Thanks 🙏

Basil MSLMANI

On Mar 1, 2019, at 8:48 PM, Tommy Muir <notifications@github.com<mailto:notifications@github.com>> wrote:


Fixed in 2.0

**Comment by basilmslmani** [comment]
Where I can get the dependency (libbulluten)?

Basil MSLMANI

On Mar 1, 2019, at 8:48 PM, Tommy Muir <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #4<https://github.com/Muirey03/Cr4shed/issues/4>.

**Comment by Muirey03** [comment]
http://limneos.net/repo/
