### ISSUE TITLE
Cr4shed causes Bitwarden Autofill in Safari to crash

### ISSUE THREAD

**Issue by gkeep** [Muirey03/Cr4shed#40]
Gist with crash logs: https://gist.github.com/gkeep/8103aad02942c76f364669088497c323

Right now, cr4shed causes Autofill in Safari to crash, but in versions before 4.0 it also caused the Bitwarden app to crash.

For now, I've blacklisted `BitwardeniOSAutofill` and `BitwardeniOS`, which fixed the crashes.

Cr4shed version: 4.1.1-1
iOS: 12.4

**Comment by Muirey03** [comment]
Are you sure Cr4shed is actually *causing* the crashes and not just *reporting* them?

**Comment by gkeep** [comment]
Yes, I have disabled Cr4shed with TweakConfigurator and did not experience them.

**Comment by gkeep** [comment]
Don't see a point in keeping this issue open. I agree, though, it's very likely that Cr4shed was just reporting the crashes.
