### ISSUE TITLE
Upgrade from 4.1.1 to 4.1.2 staying in Cydia upgrade queue

### ISSUE THREAD

**Issue by nakozak** [Muirey03/Cr4shed#45]
This is due to the new libMRYIPC dependency. If a user does not have the dynastic repo installed, cr4shed will fail to upgrade citing the com.muirey03.libmryipc as the reason. Cr4shed then stays in the Cydia Upgrade queue. Adding the dynastic repo resolves this issue.

**Comment by Muirey03** [comment]
This is not an issue. Cr4shed has a dependency, so the repo that the dependency is on needs to be added of course.
