### ISSUE TITLE
More information on what caused the crash issue?

### ISSUE THREAD

**Issue by JoelPeterPage** [Muirey03/Cr4shed#50]
Are you planning on allowing more information on crashes?
I’m guessing these are to do with the jailbreak bug Itself!
![0853F47E-A726-4ACD-9619-C215776073F6](https://user-images.githubusercontent.com/9304573/79056596-47849a80-7c97-11ea-912b-281134e8d49e.png)
![C23DAFD1-799C-4CDC-B903-C2DDBCDE3A2C](https://user-images.githubusercontent.com/9304573/79056597-4a7f8b00-7c97-11ea-9bf7-4cf2860806ba.png)

**Comment by Muirey03** [comment]
No more information other than what is in the log is possible.
