### ISSUE TITLE
Libnotificationd keeps crashing almost every time I get a notification from something else 

### ISSUE THREAD

**Issue by giannakillz** [Muirey03/Cr4shed#53]
Cr4shed was working fine for a week then out of no where constant libnotificationd crashed throughout the whole day, mainly triggered by getting a notification. Problem is solved when I uninstall Cr4shed. I don’t have anything installed that changes stock notifications and didn’t make any changes before it started happening. I have the latest version, using uncover 5.2.0 on iPhone 8plus on iOS 13.5
![BEDAA01F-5CE2-4152-ADD8-06782BB9FF77](https://user-images.githubusercontent.com/66619183/85212100-537a8180-b304-11ea-8b77-8d2b8b273e96.png)

**Comment by Muirey03** [comment]
Don't contact me, I didn't make libnotifications.
