### ISSUE TITLE
Cr4shed problem

### ISSUE THREAD

**Issue by cohiba55555** [Muirey03/Cr4shed#55]
I downloaded it and no app on springboard and this notification pops up continues can’t stop it lol “ you would like to send me notifications “ I can’t stop it pretty frustrating

**Comment by Muirey03** [comment]
Run `uicache` to make the app appear on your homescreen then you can allow notifications for it.

**Comment by cohiba55555** [comment]
Lol I’m 72 and some thing I don’t know how do I run that? Thanks and what
about your request to allow notifications that won’t stop popping up?

**Comment by cohiba55555** [comment]
I really appreciate your help
