### ISSUE TITLE
Cr4shed only logs uncaught exceptions

### ISSUE THREAD

**Issue by NSExceptional** [Muirey03/Cr4shed#59]
Cr4shed—unlike Crash Reporter—will only show crashes related to uncaught NSExceptions, AFAICT. If you dereference a null pointer or divide by 0 or something, Cr4shed won't know about it.

**Comment by Muirey03** [comment]
It should do, that's what the cr4shedmach code does. What device and version are you testing this on?

**Comment by NSExceptional** [comment]
Oh, interesting. I've quite literally never had it work on anything but exceptions so I just assumed that's all it could do.

iOS 14 iPhone X

**Comment by NSExceptional** [comment]
For anyone else reading this, apparently a class was renamed on iOS 14 and broke this functionality and a fix will be out soon

**Comment by Muirey03** [comment]
Fixed in aae7faa

**Comment by NSExceptional** [comment]
@Muirey03 This has, so far, not fixed anything for me

**Comment by NSExceptional** [comment]
False alarm, I had CrashReporter installed too and it was conflicting, sorry
