### ISSUE TITLE
App is empty 

### ISSUE THREAD

**Issue by AndrisBorbas** [Muirey03/Cr4shed#9]
There is only an edit button inside the app, everything else is just plain white. Im on iOS 12.1.1 iPhone 7

**Comment by Kunderscore** [comment]
app is empty could suggest there hasn't been any crashes, or are you expecting crash logs then, if you are perhaps next time you should mention it will reporting issues.
So please explain if this is a case of the former or the latter.

**Comment by Muirey03** [comment]
Now that RocketBootstrap has been updated, all crashes in all processes should be reported. (Make sure you update Cr4shed to v.2.0.4)
